language: node_js
node_js:
  - "8"
  - "node"
os:
  - osx
  - linux
osx_image: xcode9.4
dist: trusty
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_script:
  - npm install

script:
  - npm start
  - npm run-script package
  - npm run-script dist

after_script:
  - cd ./outApp
  - git init
  - git config user.name "frank-xjh"
  - git config user.email "frank99-xu@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:releases
  - cd ./dist
  - git init
  - git config user.name "frank-xjh"
  - git config user.email "frank99-xu@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:releases-dist

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/frank-xjh/FeCalculator.git